apiVersion: integration/v1
kind: Integration
name: gcp-iam
channel: stable
version: v20200514
summary: Google Cloud Platform IAM
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-gcp-iam
source: https://github.com/relay-integrations/relay-gcp-iam

description: |
   Identity and Access Management (IAM) lets you create and manage permissions for Google Cloud resources. IAM unifies access control for Google Cloud services into a single system and presents a consistent set of operations.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- gcp
- permissions
- rbac
- relay integration
